# Generated by Django 5.0.1 on 2024-01-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_product_alter_product_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='describtion',
            new_name='description',
        ),
    ]
